### ISSUE TITLE
Remove code -- inner key is no longer received from caches

### ISSUE THREAD

**Issue by GhadaAlmashaqbeh** [Cache-Cash/CacheCash#145]
https://github.com/Cache-Cash/CacheCash/blob/784a0ebca26a5b6bce49e507c4e0c4a5bc837b2d/javascript_client/data_service_client.js#L532

This part of the code is not needed, nor the messages format/type/etc. Client does not receive the inner encryption key from caches anymore, it is extracted from masked tktL2

**Comment by GhadaAlmashaqbeh** [comment]
- Same for line 518, the parameter 'layer' is no longer needed.
- switch statement can be replaced with a simple if/else since we have one key message now.
- I cannot see why the code at lines 558 - 563 is there? the CP does not send any key messages to the client. The inner layer keys are embedded inside the masked tktL2 where the signature is verified over the tickets bundle when the clients receives it at the beginning of the service session.

**Comment by baloyan** [comment]
Yes, but we have to decrypt inner layer of data right ? which happens in the same function BTW.

**Comment by baloyan** [comment]
So, I will modify all of those stuff later.

**Comment by GhadaAlmashaqbeh** [comment]
- I guess it will be better if we have an error message at line 585 to be "generating IV failed" or something similar.
- Same for line 597, the error message must be outer layer decryption failed.

**Comment by baloyan** [comment]
Yup

**Comment by GhadaAlmashaqbeh** [comment]
This mixing of logic is sort of confusing, what you do in lines 633 - 644 by casting a fake key message that contains the inner layer key extracted from the unmasked tktL2 is not needed. You cost the client another signature verification for nothing. The keys are already covered by the batch signature inside the masked tktL2. We are striving to make our client efficient!

In those lines that are crafting an inner layer key message, replace them with a call to decrypt the data block, that is it. Trust me, it will be way better and easier to understand the code. We do not have inner layer key message anymore.

Even no need to handledatablocskpart2. When I first wrote the code the client was waiting the inner layer keys messages from caches. So this part two made sense at that time. But now no, after solving the puzzle and sending out tktL2 to caches, decrypt the data blocks immediately.

**Comment by GhadaAlmashaqbeh** [comment]
In file verify.js:
- I think it is better to change the error messages at lines 39 and 49. It is not the hashing has failed, it does not match as it is not found in tickets bundle hashes set, which means the signature verification failed.

**Comment by baloyan** [comment]
There is an issue for error messages https://github.com/Cache-Cash/CacheCash/issues/65

**Comment by baloyan** [comment]
It was implemented in PR https://github.com/Cache-Cash/CacheCash/pull/150
