### ISSUE TITLE
Outer layer problem

### ISSUE THREAD

**Issue by baloyan** [Cache-Cash/CacheCash#147]
Client sends a request to cache for every data block, and every request is parallel.
In cache side we have two sessions for handling request.

1. Handle request process batch signature and ticket request (the first request)
2.  Handle ticket lottery one. (the second request for the same data block)

So, in order to handle and process ticket lottery one we have to have some data from the first session and all data we currently keep in a `CacheDataBlockResponse` structure and some data is specific for every requested data block, but `CacheDataBlockResponse` type object we define as a common, which is wrong, because if requests are parallel data can be mixed, like outer layer key and cache sends to client a wrong data.

Solution:
1. Make a sequential requests in client side, which is the worst solution.
2. For every data block request in cache side we should create a object which contains all information, which related to only current data block, we should do it in a step 1 see above. And then in ticket lottery session we generated correct outer key for current data block.

Note that, we assume that public key is a specific ID for every client, because based on ID and block number we can specify step 1 and 2.

**Comment by baloyan** [comment]
I am working on it and implementing the second approach

**Comment by GhadaAlmashaqbeh** [comment]
Just some tiny comment please (and sorry for the tons of comments everywhere :P). In the last, I guess we should use the client ID and the request_seqno to differentiate which request belongs to which client, as the same client may request the same data block again.

And solution 1 is not good as you said, for some other reason as well, different clients could be contacting the cache asking for data blocks, so we cannot assume the sequential behavior in this case.

**Comment by baloyan** [comment]
Yes exactly, ID (public key), `request_seqno` and block number, based on that we can generated specific outer layer key.

**Comment by baloyan** [comment]
An issue was implemented in PR https://github.com/Cache-Cash/CacheCash/pull/148
