### ISSUE TITLE
Provide Application Layer Network Interface

### ISSUE THREAD

**Issue by lukpueh** [Cache-Cash/CacheCash#38]
Currently CacheCash defines its own Network Protocol on top of TCP. If we want a JavaScript Client that runs in a browser we have to use a standardized protocol that browsers can speak, like HTTP or rather its stripped down successor [websockets](https://en.wikipedia.org/wiki/WebSocket) (http-friendly handshake, less communication overhead), and their respective secure variants.

A client that uses websockets would require an update of the content providers' and caches' C implementation to also use websockets. 

A quick but less preferred alternative would be to use a websocket-to-TCP bridge like [websockify](https://github.com/novnc/websockify). I don't recommend this due to the added network cost and the state of the project.

**Comment by baloyan** [comment]
We use HTTP/HTTPS protocol and it is implemented.
